### ISSUE TITLE
Any chance you might update this in the future?

### ISSUE THREAD

**Issue by MostHated** [Pernickety/rainmeter-todo-list#1]
Hey there,
    This seemed perfect for what I was after, but I went to give it a try and unfortunately it doesn't seem like it's compatible anymore. Is there any chance you might one day be looking to go back and give it an update? I can certainly understand if not but I figured it was worth an ask.

Thanks,
-MH

**Comment by louiskueh** [comment]
![image](https://user-images.githubusercontent.com/2521843/78777696-eb1d3480-7991-11ea-844f-a3bc494ac27e.png)

Getting this error

**Comment by Resadesker** [comment]
> ![image](https://user-images.githubusercontent.com/2521843/78777696-eb1d3480-7991-11ea-844f-a3bc494ac27e.png)
> 
> Getting this error

The same problem

**Comment by rfechtner** [comment]
+1. Any alternatives out there?

**Comment by wimmatthijs** [comment]
+1 too bad, this was a nice skin... i might look into it if i have time, but that won't be for a few months

**Comment by MostHated** [comment]
I mean, It's already been nearly a year since I asked initially, what's another few months? lol. If you do ever get around to it, that would be great. 👍

**Comment by Joehuu** [comment]
Just add:

```
[DummyMeter]
Meter=String
```

to the end of `todo.ini` and it'll work.

**Comment by MostHated** [comment]
Well, I'll be damned.

**Comment by kaustubha-tapi** [comment]
[Fixed File Here](https://github.com/kaustubha-tapi/rainmeter-todo-list)

**Comment by MostHated** [comment]
I have since switched back to using linux on my desktop, but I am sure this will be appreciated.

**Comment by kaustubha-chaturvedi** [comment]
I had this problem fixed 3 years ago but I think **@Pernickety** is one whose solution should be used being original author.

**Comment by Pernickety** [comment]
Kudos @kaustubha-chaturvedi for the timely fix!  I had unintentionally abandoned the project after initial release but I'm excited to pick things back up.
