### ISSUE TITLE
Says it doesn't contain any meter and will be deactivated. File maybe damaged.

### ISSUE THREAD

**Issue by tamirazrab** [Pernickety/rainmeter-todo-list#2]
Don't know but it isn't loading any solution?

**Comment by wimmatthijs** [comment]
I second this, i think it needs to be reworked?

**Comment by ITCMD** [comment]
Same issue here. 
![image](https://user-images.githubusercontent.com/32961763/102629721-88338e00-4119-11eb-8222-71fadb46731b.png)

**Comment by Joehuu** [comment]
See https://github.com/Pernickety/rainmeter-todo-list/issues/1#issuecomment-745650196.

**Comment by kaustubha-tapi** [comment]
https://github.com/kaustubha-tapi/rainmeter-todo-list

I just added the Fixed File
